

when running: flask db upgrade

error:

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 9041236caa06, empty message
Traceback (most recent call last):
  File "/media/Dane/Workspace2/flask-security/venv/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/flask/cli.py", line 1129, in main
    cli.main()
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/flask/cli.py", line 400, in decorator
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/flask_migrate/cli.py", line 157, in upgrade
    _upgrade(directory or g.directory, revision, sql, tag, x_arg or g.x_arg)
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/alembic/script/base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/media/Dane/Workspace2/flask-security/migrations/env.py", line 113, in <module>
    run_migrations_online()
  File "/media/Dane/Workspace2/flask-security/migrations/env.py", line 107, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/media/Dane/Workspace2/flask-security/venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
    step.migration_fn(**kw)
  File "/media/Dane/Workspace2/flask-security/migrations/versions/9041236caa06_.py", line 25, in upgrade
    sa.Column('permissions', flask_security.datastore.AsaList(), nullable=True),
                             ^^^^^^^^^^^^^^
NameError: name 'flask_security' is not defined





it's probably cause by Alembic migration file that misses import for flas_security



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    ...
    sa.Column('permissions', flask_security.datastore.AsaList(), nullable=True),
    ...
    # ### end Alembic commands ###
